name: Report CI
on:
  push:
    paths:
    - 'edmaths.sty'
    - 'example-report.tex'
    - 'example-references.bib'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: edengths.tex
          args: "-pdfps -file-line-error -halt-on-error -interaction=nonstopmode"
